import re
words = [
    "about",
    "above",
    "across",
    "after",
    "against",
    "along",
    "although",
    "amid",
    "among",
    "and",
    "around",
    "as",
    "as if",
    "as long as",
    "as much as",
    "as soon as",
    "as though",
    "at",
    "because",
    "before",
    "behind",
    "below",
    "beneath",
    "beside",
    "besides",
    "between",
    "beyond",
    "but",
    "by",
    "concerning",
    "considering",
    "despite",
    "down",
    "during",
    "even if",
    "even though",
    "except",
    "for",
    "from",
    "if",
    "in",
    "in order that",
    "inside",
    "into",
    "lest",
    "like",
    "near",
    "nor",
    "now that",
    "of",
    "off",
    "on",
    "once",
    "onto",
    "or",
    "out",
    "outside",
    "over",
    "past",
    "per",
    "plus",
    "provided",
    "regarding",
    "round",
    "save",
    "since",
    "so",
    "so that",
    "than",
    "that",
    "though",
    "through",
    "till",
    "to",
    "toward",
    "towards",
    "under",
    "underneath",
    "unless",
    "unlike",
    "until",
    "unto",
    "up",
    "upon",
    "versus",
    "via",
    "what",
    "whatever",
    "when",
    "whenever",
    "where",
    "whereas",
    "wherever",
    "which",
    "whichever",
    "while",
    "who",
    "whoever",
    "whom",
    "whomever",
    "whose",
    "with",
    "within",
    "without",
    "the",
    "is",
    "are",
    "was",
    "when",
    "this",
    "a",
    "an",
    "be",
    "cannot",
    "can",
    "has",
    "have",
    "had",
    "whether",
    "yet",
]

progIsTranslatable = re.compile(r'(( |\n)(' + "|".join(words) + ")( |\n))", re.IGNORECASE)
progIsComment = re.compile(r'(\/\*(.|\n)+?\*\/)')
progIsOption = re.compile(r'(\((.|\n)+?\))')

def isTranslatable(text):
    text = progIsComment.sub('', text)
    wordLen = len(text.split(" "))
    featureLen = len(progIsTranslatable.findall(text))
    return featureLen / wordLen

